### ISSUE TITLE
Add equirectangular view of spherical videos to allow panning of sources on top

### ISSUE THREAD

**Issue by abhayap** [leomccormack/Spatial_Audio_Framework#26]
## Problem to Solve

Hi Leo, could you add an option in ambiENC to load an equirectangular view of spherically encoded videos to allow panning of sources on top of them. This would allow us to create an automation that would move the source as the objects in the video are moving.

## Current Workaround

Use a different plugin or blindly place sources for 360 spherical content.

## Additional Information

This is an example of how it works in the FB360 plugin but it only supports up to 3rd order.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/7300834/110405667-c57f2c00-8035-11eb-8b9c-b59c7dbb1f64.png">

**Comment by leomccormack** [comment]
Hi. At least currently, regarding video support, we've only added real-time "webcam" support to the visualisation plugins (powermap, dirass, sldoa), so that the user can then make an improvised acoustic camera; e.g. using the ricoh theta "webcam" on top of an Eigenmike: https://www.youtube.com/watch?v=NoeEXCoriE4
I also know some people who have "tricked" the plugins into thinking offline video playback is a webcam (I think using Max?), which is at least some workaround for that. 

As for instead _loading_ video files (also for ambiENC)... This could be explored, but I don't see us giving it a go in the near future. However, I will add it to the list : )

**Comment by abhayap** [comment]
Thanks for your reply @leomccormack
