### ISSUE TITLE
Few questions about the implementation of VBAP

### ISSUE THREAD

**Issue by jinnsjj** [leomccormack/Spatial_Audio_Framework#32]
Hello! I am reading this repos recently and confused by some details:

1. There is an `eye3` matrix in method `invertLsMtx3D` of  `saf_vbap.c`. If I understood correctly, it's an identity matrix. I wonder why `eye3` is neccessary to multiply with `tempGroup`. 
https://github.com/leomccormack/Spatial_Audio_Framework/blob/12381d6631f415839a46e05fc24ff2e70201d32b/framework/modules/saf_vbap/saf_vbap.c#L689

2. There is a logic that `omit Trianges that have an aperture larger than APERTURE_LIMIT_DEG(180)` in `findLsTriplets`. The condition is comparing the return of `acosf` and `aperture_lim` (which is pi), However, the return of `acosf` is always [0,pi].
https://github.com/leomccormack/Spatial_Audio_Framework/blob/12381d6631f415839a46e05fc24ff2e70201d32b/framework/modules/saf_vbap/saf_vbap.c#L638

Hope you can help me with these confusions, Thanks!

**Comment by leomccormack** [comment]
hi!

1. Correct, that looks pretty unnecessary! Feel free to remove it and send a PR. Otherwise, I can get round to doing this later in the week. : )
2. Also correct, 180 degrees is effectively bypassing this feature. I was hoping to add this as an optional input argument, but alas, this was a while ago and appears to have slipped under the radar. 

To be honest, although very functional, the vbap module could do with a bit of a refresh. Removing more redundant code, adding VBIP support, using optimised functions from saf_utilities_veclib more, and then updating the "panner" example to avoid gain tables (so that changing the source spread can be done in real-time). One day! : )
