### ISSUE TITLE
Function name in ambi_dec example is confusing

### ISSUE THREAD

**Issue by olilarkin** [leomccormack/Spatial_Audio_Framework#36]
https://github.com/leomccormack/Spatial_Audio_Framework/blob/e1ddc199313594e92b304d54dcfdc4b6125343aa/examples/include/ambi_dec.h#L343

Since there is another NormType

**Comment by leomccormack** [comment]
Hey!

Apologies for not getting back to this for so long! (I saw it, I forgot, I saw again, and I forgot again....)

Agreed, the naming of these two functions could have been chosen better at the time.

However, since the examples are quite well entrenched into some other projects, I'm a bit reluctant to change it unless it's creating major confusion. 

An effort has been made to describe these two functions in the comments/doxygen, which I hope helps to alleviate this, but if this is not enough, I am open to suggestions :)
